name: Update Docker Hub Description

on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
  pull_request:
    paths:
      - .github/workflows/dockerhub-description.yml
    branches:
      - main
  workflow_dispatch:

jobs:
  dockerHubDescription:
    name: Sync DockerHub Description
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: alexrashed/dockerhub-description-tests
        short-description: '1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890' # 100